# Generated by Django 5.0.7 on 2025-10-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_content', '0004_styledcontentblock'),
        ('teams', '0002_sportposition_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this team', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions'),
        ),
    ]
