# Generated by Django 5.0.7 on 2025-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_style_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for the team', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile or page URL for the team'),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for the team', max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL for the team'),
        ),
    ]
