# Generated by Django 5.0.7 on 2025-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_contact_email_team_contact_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_icon_bg',
            field=models.CharField(blank=True, default='', help_text='Optional background color for icon buttons (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_icon_color',
            field=models.CharField(blank=True, default='#212529', help_text='Hex color for contact icons (e.g., #ffffff)', max_length=7),
        ),
    ]
