# Generated by Django 5.0.7 on 2025-10-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='rules_and_regulations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='show_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='show_rules_and_regulations',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
