# Generated by Django 5.0.7 on 2025-10-21 01:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sport_history_sport_rules_and_regulations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='history',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='rules_and_regulations',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
