# Generated by Django 5.0.7 on 2025-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='custom_date',
            field=models.DateField(blank=True, help_text='Optional custom date for this article', null=True),
        ),
    ]
