# Generated by Django 5.0.7 on 2025-10-28 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_custom_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='custom_date',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Published date for this article'),
        ),
    ]
