# Generated by Django 5.0.7 on 2025-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#0A192F', help_text='Navy Blue - Main brand color', max_length=7)),
                ('accent_color', models.CharField(default='#00BFA6', help_text='Teal - Accent color', max_length=7)),
                ('secondary_color', models.CharField(default='#F5F5F5', help_text='Light Gray - Secondary color', max_length=7)),
                ('highlight_color', models.CharField(default='#FF9800', help_text='Orange - Highlight color', max_length=7)),
                ('background_type', models.CharField(choices=[('color', 'Solid Color'), ('image', 'Background Image'), ('gradient', 'Gradient')], default='color', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color', max_length=7)),
                ('background_image', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='themes/')),
                ('background_gradient', models.CharField(blank=True, help_text='CSS gradient (e.g., linear-gradient(45deg, #ff0000, #0000ff))', max_length=200)),
                ('font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Nunito', 'Nunito'), ('Source Sans Pro', 'Source Sans Pro')], default='Inter', max_length=50)),
                ('font_size_base', models.PositiveIntegerField(default=16, help_text='Base font size in pixels')),
                ('heading_font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Nunito', 'Nunito'), ('Source Sans Pro', 'Source Sans Pro')], default='Inter', max_length=50)),
                ('text_primary', models.CharField(default='#2C3E50', help_text='Primary text color', max_length=7)),
                ('text_secondary', models.CharField(default='#6C757D', help_text='Secondary text color', max_length=7)),
                ('text_light', models.CharField(default='#FFFFFF', help_text='Light text color', max_length=7)),
                ('navbar_background', models.CharField(default='#0A192F', help_text='Navbar background color', max_length=7)),
                ('navbar_text_color', models.CharField(default='#FFFFFF', help_text='Navbar text color', max_length=7)),
                ('navbar_hover_color', models.CharField(default='#00BFA6', help_text='Navbar hover color', max_length=7)),
                ('navbar_style', models.CharField(choices=[('solid', 'Solid'), ('transparent', 'Transparent'), ('glass', 'Glass Effect')], default='solid', max_length=20)),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('pill', 'Pill')], default='rounded', max_length=20)),
                ('button_primary_bg', models.CharField(default='#0A192F', help_text='Primary button background', max_length=7)),
                ('button_primary_text', models.CharField(default='#FFFFFF', help_text='Primary button text', max_length=7)),
                ('button_secondary_bg', models.CharField(default='#00BFA6', help_text='Secondary button background', max_length=7)),
                ('button_secondary_text', models.CharField(default='#FFFFFF', help_text='Secondary button text', max_length=7)),
                ('link_color', models.CharField(default='#00BFA6', help_text='Link color', max_length=7)),
                ('link_hover_color', models.CharField(default='#FF9800', help_text='Link hover color', max_length=7)),
                ('link_underline', models.BooleanField(default=False, help_text='Show underline on links')),
                ('card_background', models.CharField(default='#FFFFFF', help_text='Card background color', max_length=7)),
                ('card_border_color', models.CharField(default='#E9ECEF', help_text='Card border color', max_length=7)),
                ('card_shadow', models.BooleanField(default=True, help_text='Enable card shadows')),
                ('card_border_radius', models.PositiveIntegerField(default=15, help_text='Card border radius in pixels')),
                ('footer_background', models.CharField(default='#0A192F', help_text='Footer background color', max_length=7)),
                ('footer_text_color', models.CharField(default='#FFFFFF', help_text='Footer text color', max_length=7)),
                ('footer_link_color', models.CharField(default='#00BFA6', help_text='Footer link color', max_length=7)),
                ('container_max_width', models.CharField(choices=[('container', 'Standard'), ('container-fluid', 'Full Width'), ('container-xl', 'Extra Large'), ('container-lg', 'Large')], default='container', max_length=20)),
                ('section_padding', models.PositiveIntegerField(default=80, help_text='Section padding in pixels')),
                ('enable_animations', models.BooleanField(default=True, help_text='Enable AOS animations')),
                ('animation_duration', models.PositiveIntegerField(default=800, help_text='Animation duration in milliseconds')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Theme',
                'verbose_name_plural': 'Website Themes',
            },
        ),
    ]
