# Generated by Django 5.0.7 on 2025-10-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_websitetheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetheme',
            name='font_family',
            field=models.CharField(choices=[('Inter', 'Inter - Modern & Clean'), ('Roboto', 'Roboto - Google Material'), ('Open Sans', 'Open Sans - Humanist'), ('Lato', 'Lato - Semi-rounded'), ('Poppins', 'Poppins - Geometric'), ('Montserrat', 'Montserrat - Urban'), ('Nunito', 'Nunito - Rounded'), ('Source Sans Pro', 'Source Sans Pro - Adobe'), ('Work Sans', 'Work Sans - Professional'), ('Fira Sans', 'Fira Sans - Mozilla'), ('IBM Plex Sans', 'IBM Plex Sans - Corporate'), ('Noto Sans', 'Noto Sans - Google'), ('Manrope', 'Manrope - Modern'), ('DM Sans', 'DM Sans - Editorial'), ('Plus Jakarta Sans', 'Plus Jakarta Sans - Indonesian'), ('Figtree', 'Figtree - Friendly'), ('Satoshi', 'Satoshi - Premium'), ('Cabinet Grotesk', 'Cabinet Grotesk - Display'), ('Space Grotesk', 'Space Grotesk - Futuristic'), ('Outfit', 'Outfit - Geometric')], default='Inter', max_length=50),
        ),
        migrations.AlterField(
            model_name='websitetheme',
            name='heading_font_family',
            field=models.CharField(choices=[('Inter', 'Inter - Modern & Clean'), ('Roboto', 'Roboto - Google Material'), ('Open Sans', 'Open Sans - Humanist'), ('Lato', 'Lato - Semi-rounded'), ('Poppins', 'Poppins - Geometric'), ('Montserrat', 'Montserrat - Urban'), ('Nunito', 'Nunito - Rounded'), ('Source Sans Pro', 'Source Sans Pro - Adobe'), ('Work Sans', 'Work Sans - Professional'), ('Fira Sans', 'Fira Sans - Mozilla'), ('IBM Plex Sans', 'IBM Plex Sans - Corporate'), ('Noto Sans', 'Noto Sans - Google'), ('Manrope', 'Manrope - Modern'), ('DM Sans', 'DM Sans - Editorial'), ('Plus Jakarta Sans', 'Plus Jakarta Sans - Indonesian'), ('Figtree', 'Figtree - Friendly'), ('Satoshi', 'Satoshi - Premium'), ('Cabinet Grotesk', 'Cabinet Grotesk - Display'), ('Space Grotesk', 'Space Grotesk - Futuristic'), ('Outfit', 'Outfit - Geometric')], default='Inter', max_length=50),
        ),
    ]
