# Generated by Django 5.0.7 on 2025-10-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutsection_aboutteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The name of the value (e.g., 'Integrity', 'Innovation')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of this value')),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-heart', 'fas fa-lightbulb')", max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Optional image representing this value', null=True, upload_to='values/')),
                ('color', models.CharField(default='#00BFA6', help_text='Hex color code for this value', max_length=7)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this value prominently')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['order', 'title'],
            },
        ),
    ]
