# Generated by Django 5.0.7 on 2025-10-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='animation_delay',
            field=models.PositiveIntegerField(default=0, help_text='Animation delay in milliseconds'),
        ),
        migrations.AddField(
            model_name='value',
            name='animation_duration',
            field=models.PositiveIntegerField(default=800, help_text='Animation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='value',
            name='animation_type',
            field=models.CharField(choices=[('none', 'No Animation'), ('fade', 'Fade In'), ('slide', 'Slide Up'), ('zoom', 'Zoom In'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='fade', help_text='Animation effect for this value card', max_length=20),
        ),
        migrations.AddField(
            model_name='value',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color (used for solid or gradient)', max_length=7),
        ),
        migrations.AddField(
            model_name='value',
            name='background_gradient',
            field=models.CharField(blank=True, help_text='CSS gradient (e.g., linear-gradient(45deg, #ff0000, #0000ff))', max_length=200),
        ),
        migrations.AddField(
            model_name='value',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for this value card', null=True, upload_to='values/backgrounds/'),
        ),
        migrations.AddField(
            model_name='value',
            name='background_overlay',
            field=models.CharField(default='#000000', help_text='Overlay color for background image (with opacity)', max_length=7),
        ),
        migrations.AddField(
            model_name='value',
            name='background_overlay_opacity',
            field=models.FloatField(default=0.3, help_text='Overlay opacity (0.0 = transparent, 1.0 = opaque)'),
        ),
        migrations.AddField(
            model_name='value',
            name='background_type',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image')], default='solid', help_text='Choose the background type for this value card', max_length=20),
        ),
    ]
