# Generated by Django 5.0.7 on 2025-10-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_value_animation_delay_value_animation_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='section_animation_duration',
            field=models.PositiveIntegerField(default=1000, help_text='Section animation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_animation_type',
            field=models.CharField(choices=[('none', 'No Animation'), ('fade', 'Fade In'), ('slide', 'Slide Up'), ('zoom', 'Zoom In'), ('parallax', 'Parallax')], default='none', help_text='Animation effect for this section', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_background_color',
            field=models.CharField(default='#F8F9FA', help_text='Section background color', max_length=7),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_background_gradient',
            field=models.CharField(blank=True, help_text='CSS gradient for section background (e.g., linear-gradient(45deg, #ff0000, #0000ff))', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_background_image',
            field=models.ImageField(blank=True, help_text='Background image for this section', null=True, upload_to='about/backgrounds/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_background_overlay',
            field=models.CharField(default='#000000', help_text='Overlay color for section background image', max_length=7),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_background_overlay_opacity',
            field=models.FloatField(default=0.3, help_text='Section overlay opacity (0.0 = transparent, 1.0 = opaque)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_background_type',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image'), ('pattern', 'Pattern')], default='solid', help_text='Choose the background type for this section', max_length=20),
        ),
    ]
