# Generated by Django 5.0.7 on 2025-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutsection_section_animation_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='section_glass_backdrop',
            field=models.BooleanField(default=True, help_text='Enable backdrop filter for glass effect'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_glass_blur',
            field=models.PositiveIntegerField(default=10, help_text='Glass effect blur intensity (0-50px)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_glass_border',
            field=models.BooleanField(default=True, help_text='Add subtle border to glass effect'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_glass_effect',
            field=models.BooleanField(default=False, help_text='Enable glass morphism effect for this section'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='section_glass_opacity',
            field=models.FloatField(default=0.2, help_text='Glass effect opacity (0.0 = transparent, 1.0 = opaque)'),
        ),
    ]
