# Generated by Django 5.0.7 on 2025-10-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutsection_section_glass_backdrop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutteammember',
            name='animation_delay',
            field=models.PositiveIntegerField(default=0, help_text='Animation delay in milliseconds'),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='animation_duration',
            field=models.PositiveIntegerField(default=1000, help_text='Animation duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='animation_type',
            field=models.CharField(choices=[('none', 'No Animation'), ('fade', 'Fade In'), ('slide', 'Slide Up'), ('zoom', 'Zoom In'), ('bounce', 'Bounce In')], default='fade', help_text='Animation effect for this team member card', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Team member card background color', max_length=7),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='background_gradient',
            field=models.CharField(blank=True, help_text='CSS gradient for team member card background (e.g., linear-gradient(45deg, #ff0000, #0000ff))', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for this team member card', null=True, upload_to='about/team/backgrounds/'),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='background_overlay',
            field=models.CharField(default='#000000', help_text='Overlay color for team member card background image', max_length=7),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='background_overlay_opacity',
            field=models.FloatField(default=0.3, help_text='Team member card overlay opacity (0.0 = transparent, 1.0 = opaque)'),
        ),
        migrations.AddField(
            model_name='aboutteammember',
            name='background_type',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image'), ('pattern', 'Pattern')], default='solid', help_text='Choose the background type for this team member card', max_length=20),
        ),
    ]
