# Generated by Django 5.0.7 on 2025-10-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutteammember_animation_delay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('mission', 'Mission Section'), ('vision', 'Vision Section'), ('values', 'Values Section'), ('team', 'Team Section'), ('history', 'History Section'), ('achievements', 'Achievements Section'), ('stats', 'Stats Section')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="The statistic number or text (e.g., '200+', '10K')", max_length=50)),
                ('title', models.CharField(help_text="Title of the statistic (e.g., 'Projects Completed')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional short description for the stat')),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-users')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
    ]
