# Generated by Django 5.0.7 on 2025-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aboutsection_section_type_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Physical address of the organization', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('facebook_url', models.URLField(blank=True, help_text='URL to Facebook profile')),
                ('twitter_url', models.URLField(blank=True, help_text='URL to Twitter profile')),
                ('instagram_url', models.URLField(blank=True, help_text='URL to Instagram profile')),
                ('linkedin_url', models.URLField(blank=True, help_text='URL to LinkedIn profile')),
                ('youtube_url', models.URLField(blank=True, help_text='URL to YouTube channel')),
                ('quick_links_json', models.JSONField(blank=True, help_text="JSON array of quick links, e.g., [{'name': 'About Us', 'url': '/about'}]", null=True)),
                ('copyright_text', models.CharField(blank=True, default='© 2025 Your Organization. All rights reserved.', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Logo to display in the footer', null=True, upload_to='footer/')),
                ('description', models.TextField(blank=True, help_text='Short description or mission statement in the footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
            },
        ),
    ]
