# Generated by Django 5.0.7 on 2025-10-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='quick_links_json',
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the link', max_length=100)),
                ('url', models.URLField(help_text='URL for the link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the link appears')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footer')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
    ]
