# Generated by Django 5.0.7 on 2025-10-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_footer_quick_links_json_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='quick_links_json',
            field=models.JSONField(blank=True, help_text="JSON array of quick links, e.g., [{'name': 'About Us', 'url': '/about'}]", null=True),
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
