# Generated by Django 5.0.7 on 2025-10-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_footer_quick_links_json_delete_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the quick link', max_length=100)),
                ('url', models.URLField(help_text='URL for the quick link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the link appears')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='core.footer')),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['order'],
            },
        ),
    ]
