# Generated by Django 5.0.7 on 2025-10-20 16:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quicklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
