# Generated by Django 5.0.7 on 2025-10-21 01:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_aboutsection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Short description or mission statement in the footer'),
        ),
    ]
