# Generated by Django 5.0.7 on 2025-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognition/')),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g. 'fas fa-trophy')", max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_clickable', models.BooleanField(default=True, help_text='If true, card is clickable and links to URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recognition & Achievement',
                'verbose_name_plural': 'Recognition & Achievements',
                'ordering': ['-created_at'],
            },
        ),
    ]
