# Generated by Django 5.0.7 on 2025-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_recognitionachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code for popup background', max_length=7),
        ),
        migrations.AddField(
            model_name='popup',
            name='text_color',
            field=models.CharField(default='#212529', help_text='Hex color code for popup text', max_length=7),
        ),
    ]
