# Generated by Django 5.0.7 on 2025-10-26 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogpreviewblock_calltoactionblock_contactformblock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobannerblock',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='herobannerblock',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='herobannerblock',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='herobannerblock',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='herobannerblock',
            name='title',
        ),
        migrations.AddField(
            model_name='herobannerblock',
            name='heading',
            field=models.CharField(blank=True, help_text='Optional heading for the hero section', max_length=200),
        ),
        migrations.CreateModel(
            name='HeroSlideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='blocks/hero/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.herobannerblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
