# Generated by Django 5.0.7 on 2025-10-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_herobannerblock_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color (hex code)', max_length=7)),
                ('background_image', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='backgrounds/')),
                ('background_image_opacity', models.FloatField(default=1.0, help_text='Background image opacity (0.0-1.0)')),
                ('text_color', models.CharField(default='#212529', help_text='Text color (hex code)', max_length=7)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', help_text='Text alignment', max_length=10)),
                ('padding_top', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='medium', help_text='Top padding', max_length=10)),
                ('padding_bottom', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='medium', help_text='Bottom padding', max_length=10)),
                ('padding_left', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Left padding', max_length=10)),
                ('padding_right', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Right padding', max_length=10)),
                ('margin_top', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Top margin', max_length=10)),
                ('margin_bottom', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Bottom margin', max_length=10)),
                ('container_width', models.CharField(choices=[('full', 'Full Width'), ('boxed', 'Boxed'), ('narrow', 'Narrow')], default='boxed', help_text='Container width', max_length=10)),
                ('border_radius', models.PositiveIntegerField(default=8, help_text='Border radius in pixels (0-50)')),
                ('shadow', models.BooleanField(default=False, help_text='Add shadow effect')),
                ('animate_on_scroll', models.BooleanField(default=True, help_text='Enable scroll animations')),
                ('hover_effect', models.CharField(choices=[('none', 'No Effect'), ('lift', 'Lift Up'), ('zoom', 'Zoom In'), ('fade', 'Fade'), ('glow', 'Glow')], default='none', help_text='Hover effect for the block', max_length=20)),
                ('custom_class', models.CharField(blank=True, help_text='Additional CSS classes', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Style Options',
                'verbose_name_plural': 'Style Options',
            },
        ),
        migrations.AddField(
            model_name='blogpreviewblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='calltoactionblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='contactformblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='counterstatsblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='faqblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='featurehighlightsblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='footerinfoblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='galleryblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='herobannerblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='teammemberblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='testimonialblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='textimageblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='timelineblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='twocolumntextblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
        migrations.AddField(
            model_name='videoembedblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.styleoptions'),
        ),
    ]
