# Generated by Django 5.0.7 on 2025-10-27 05:51

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_block_block_type_remove_block_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('events', 'Events Page'), ('news', 'News Page'), ('sports', 'Sports Page'), ('teams', 'Teams Page'), ('gallery', 'Gallery Page'), ('about', 'About Page'), ('contact', 'Contact Page')], max_length=20, unique=True)),
                ('title', models.CharField(default='Welcome', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('background_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image')], default='gradient', max_length=20)),
                ('background_color', models.CharField(default='#0A192F', help_text='Solid background color', max_length=7)),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, var(--primary-color) 0%, var(--accent-color) 100%)', help_text='CSS gradient (e.g., linear-gradient(45deg, #ff0000, #0000ff))', max_length=200)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the hero section', null=True, upload_to='page_heroes/')),
                ('background_overlay', models.CharField(default='#000000', help_text='Overlay color for background image', max_length=7)),
                ('background_overlay_opacity', models.FloatField(default=0.3, help_text='Overlay opacity (0.0 = transparent, 1.0 = opaque)')),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color', max_length=7)),
                ('title_size', models.CharField(choices=[('display-3', 'Extra Large'), ('display-4', 'Large'), ('display-5', 'Medium'), ('display-6', 'Small')], default='display-3', max_length=20)),
                ('show_event_count', models.BooleanField(default=True, help_text='Show total events count')),
                ('show_sports_count', models.BooleanField(default=True, help_text='Show sports categories count')),
                ('custom_stat_1_text', models.CharField(blank=True, max_length=50)),
                ('custom_stat_1_value', models.CharField(blank=True, max_length=50)),
                ('custom_stat_2_text', models.CharField(blank=True, max_length=50)),
                ('custom_stat_2_value', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(choices=[('min-vh-25', 'Small (25vh)'), ('min-vh-50', 'Medium (50vh)'), ('min-vh-75', 'Large (75vh)'), ('min-vh-100', 'Full Screen (100vh)')], default='min-vh-50', max_length=20)),
                ('enable_animation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Heroes',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AlterModelOptions(
            name='popup',
            options={'verbose_name': 'Popup', 'verbose_name_plural': 'Popups'},
        ),
        migrations.AddField(
            model_name='popup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='popup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code for section background', max_length=7),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_animation_duration',
            field=models.PositiveIntegerField(default=1000, help_text='Animation duration in milliseconds'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_animation_type',
            field=models.CharField(choices=[('none', 'No Animation'), ('fade', 'Fade In'), ('slide', 'Slide Up'), ('zoom', 'Zoom In'), ('bounce', 'Bounce')], default='fade', help_text='Animation effect for this section', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Section background color', max_length=7),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_background_image',
            field=models.ImageField(blank=True, help_text='Background image for this section', null=True, upload_to='about/section_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_background_overlay_opacity',
            field=models.FloatField(default=0.3, help_text='Section background overlay opacity (0.0 = transparent, 1.0 = opaque)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_background_type',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image')], default='solid', help_text='Choose the background type for this section', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_glass_backdrop',
            field=models.BooleanField(default=True, help_text='Apply backdrop filter'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_glass_blur',
            field=models.PositiveIntegerField(default=10, help_text='Glass blur amount in pixels'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_glass_border',
            field=models.BooleanField(default=True, help_text='Show glass border'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_glass_effect',
            field=models.BooleanField(default=False, help_text='Enable glass morphism effect'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_glass_opacity',
            field=models.FloatField(default=0.8, help_text='Glass background opacity (0.0 = transparent, 1.0 = opaque)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('mission', 'Mission Section'), ('vision', 'Vision Section'), ('values', 'Values Section'), ('team', 'Team Section'), ('history', 'History Section'), ('achievements', 'Achievements Section'), ('stats', 'Stats Section')], default='hero', help_text='Type of about section', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='text_color',
            field=models.CharField(default='#212529', help_text='Hex color code for section text', max_length=7),
        ),
    ]
