# Generated by Django 5.0.7 on 2025-10-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_pagehero_alter_aboutsection_options_and_more'),
        ('teams', '0002_sportposition_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutteammember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_members', to='teams.team'),
        ),
    ]
