# Generated by Django 5.0.7 on 2025-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_aboutteammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for this section', max_length=254),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='contact_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile or page URL'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for this section', max_length=30),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='contact_twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
    ]
