# Generated by Django 5.0.7 on 2025-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='NSCPL PRIVATE LIMITED', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline or description', max_length=300)),
                ('address_line_1', models.CharField(help_text='Street address', max_length=200)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('primary_phone', models.CharField(help_text='Main contact number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, help_text='Alternative contact number', max_length=20)),
                ('primary_email', models.EmailField(help_text='Main contact email', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, help_text='Alternative contact email', max_length=254)),
                ('business_hours_weekdays', models.CharField(default='Monday - Friday: 9:00 AM - 6:00 PM', help_text='Weekday business hours', max_length=100)),
                ('business_hours_saturday', models.CharField(default='Saturday: 10:00 AM - 4:00 PM', help_text='Saturday business hours', max_length=100)),
                ('business_hours_sunday', models.CharField(default='Sunday: Closed', help_text='Sunday business hours', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Company website URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn company page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display', max_digits=9, null=True)),
                ('map_zoom', models.PositiveIntegerField(default=15, help_text='Map zoom level (1-20)')),
                ('show_map', models.BooleanField(default=True, help_text='Show map on contact page')),
                ('show_social_links', models.BooleanField(default=True, help_text='Show social media links')),
                ('show_business_hours', models.BooleanField(default=True, help_text='Show business hours')),
                ('background_color', models.CharField(default='#F8F9FA', help_text='Contact section background color', max_length=7)),
                ('text_color', models.CharField(default='#2C3E50', help_text='Contact section text color', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable contact information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important message')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
