# Generated by Django 5.0.7 on 2025-10-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_address',
            field=models.CharField(blank=True, help_text='Full address for Google Maps (will auto-populate coordinates)', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display (auto-generated from address)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display (auto-generated from address)', max_digits=9, null=True),
        ),
    ]
