# Generated by Django 5.0.7 on 2025-10-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo_map_address_alter_contactinfo_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps embed iframe code (paste the full iframe tag here)'),
        ),
    ]
