# Generated by Django 5.0.7 on 2025-10-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactinfo_map_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='background_gradient',
            field=models.CharField(blank=True, help_text='CSS gradient value (e.g., linear-gradient(to right, #ff0000, #0000ff))', max_length=500),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for contact section', upload_to='contact/backgrounds/'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='background_type',
            field=models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='color', help_text='Type of background for the contact section', max_length=20),
        ),
    ]
