# Generated by Django 5.0.7 on 2025-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('faster_bowler', models.CharField(blank=True, choices=[('right_arm', 'Right arm'), ('left_arm', 'Left arm')], max_length=20, null=True)),
                ('spin_bowler', models.CharField(blank=True, choices=[('right_arm_off_break', 'Right arm off break'), ('right_arm_leg_break', 'Right arm leg break'), ('left_arm_off_break', 'Left arm off break')], max_length=30, null=True)),
                ('right_hand_batter', models.BooleanField(default=False)),
                ('left_hand_batter', models.BooleanField(default=False)),
                ('playing_role', models.CharField(blank=True, choices=[('opening_batter', 'Opening Batter'), ('middle_order_batter', 'Middle Order Batter'), ('batting_all_rounder', 'Batting All Rounder'), ('bowling_all_rounder', 'Bowling all rounder'), ('wicket_keeper', 'Wicket keeper')], max_length=50, null=True)),
                ('declaration_past_tournament', models.BooleanField(default=False)),
                ('declaration_parents_aware', models.BooleanField(default=False)),
                ('declaration_indemnify_organizers', models.BooleanField(default=False)),
                ('declaration_emergency_care', models.BooleanField(default=False)),
                ('declaration_photo_video_consent', models.BooleanField(default=False)),
                ('declaration_true_info', models.BooleanField(default=False)),
                ('registration_no_issued', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
