# Generated by Django 5.0.7 on 2025-10-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/'),
        ),
    ]
