# Generated by Django 5.0.7 on 2025-10-20 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_playerregistration_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerregistration',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='left_hand_batter',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='playing_role',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='registration_no_issued',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='right_hand_batter',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='whatsapp_no',
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='batting_proficiency',
            field=models.CharField(blank=True, choices=[('Right Hand Batter', 'Right Hand Batter'), ('Left Hand Batter', 'Left Hand Batter')], max_length=50, null=True, verbose_name='Batting Proficiency'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='country',
            field=models.CharField(default='India', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Contact No.'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='physically_fit',
            field=models.BooleanField(default=False, verbose_name='Are you physically fit (in all aspects) to attend the trials?'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='primary_playing_role',
            field=models.CharField(choices=[('Opening Batter', 'Opening Batter'), ('Middle Order Batter', 'Middle Order Batter'), ('Batting All Rounder', 'Batting All Rounder'), ('Bowling All Rounder', 'Bowling All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], default='Opening Batter', max_length=50, verbose_name='Primary Playing Role'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='secondary_playing_role',
            field=models.CharField(blank=True, choices=[('Opening Batter', 'Opening Batter'), ('Middle Order Batter', 'Middle Order Batter'), ('Batting All Rounder', 'Batting All Rounder'), ('Bowling All Rounder', 'Bowling All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], max_length=50, null=True, verbose_name='Secondary Playing Role'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Whatsapp No.'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='zip_code',
            field=models.CharField(default='', max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='declaration_emergency_care',
            field=models.BooleanField(default=False, verbose_name='I hereby give my consent for emergency medical care prescribed by authorized doctor and that this care may be giving under whatever condition are necessary to preserve the my life our well-being .the costs shall be come by me /my family.'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='declaration_indemnify_organizers',
            field=models.BooleanField(default=False, verbose_name='I hereby indemnify the organizers (and all associated of the organizers) from any casualty / mishap/any loss to me / my property during the process of attending the trials.'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='declaration_parents_aware',
            field=models.BooleanField(default=False, verbose_name='I hereby declare that my parents are aware of my participation in the trial and have no objection of whatsoever. I have informed my parents about the rules / terms and condition of the event and that they indorse my signing of this declaration on there behalf as well.'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='declaration_past_tournament',
            field=models.BooleanField(default=False, verbose_name='I hereby declare that I have not played in any of the hard ball cricket tournament in the past.'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='declaration_photo_video_consent',
            field=models.BooleanField(default=False, verbose_name='I hereby give my consent to the organizer to take photographs video recording and / or sound recording of my participation in documenting the activities.'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='declaration_true_info',
            field=models.BooleanField(default=False, verbose_name='I hereby declare that all the details given above in the registration form are true and correct to the best of my knowledge and belief . In the event of any information being found false or incorrect or myself being found not eligible in terms of eligibility criteria for the participation . My name is liable to be cancelled without any notice.'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='faster_bowler',
            field=models.CharField(blank=True, choices=[('Right arm', 'Right arm'), ('Left arm', 'Left arm')], max_length=50, null=True, verbose_name='Faster Bowlers'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='fathers_name',
            field=models.CharField(max_length=100, verbose_name="FATHER'S NAME"),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='FIRST NAME'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='spin_bowler',
            field=models.CharField(blank=True, choices=[('Right arm off break', 'Right arm off break'), ('Left arm off break', 'Left arm off break'), ('Right arm leg break', 'Right arm leg break')], max_length=50, null=True, verbose_name='Spin Bowlers'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='sur_name',
            field=models.CharField(max_length=100, verbose_name='SUR NAME'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Transaction Screenshot'),
        ),
    ]
