# Generated by Django 5.0.7 on 2025-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_playerregistration_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players_photos/', verbose_name="Player's Photo"),
        ),
    ]
