# Generated by Django 5.0.7 on 2025-10-20 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_playerregistration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='date_of_event',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Event'),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='venue',
            field=models.CharField(default='', max_length=255, verbose_name='Venue'),
        ),
    ]
