# Generated by Django 5.0.7 on 2025-10-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_playerregistration_date_of_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
