# Generated by Django 5.0.7 on 2025-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_playerregistration_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Mark this as the active registration page setting')),
                ('primary_color', models.CharField(default='#0A192F', max_length=7)),
                ('accent_color', models.CharField(default='#00BFA6', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_color', models.CharField(default='#2C3E50', max_length=7)),
                ('button_primary_bg', models.CharField(default='#0A192F', max_length=7)),
                ('button_primary_text', models.CharField(default='#FFFFFF', max_length=7)),
                ('card_background', models.CharField(default='#FFFFFF', max_length=7)),
                ('card_border_color', models.CharField(default='#E9ECEF', max_length=7)),
                ('card_border_radius', models.PositiveIntegerField(default=8)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('font_size_base', models.PositiveIntegerField(default=16)),
                ('custom_css', models.TextField(blank=True, help_text='Optional custom CSS to apply to the registration page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Page Setting',
                'verbose_name_plural': 'Registration Page Settings',
            },
        ),
    ]
