# Generated by Django 5.0.7 on 2025-10-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_registrationpagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpagesetting',
            name='heading_color',
            field=models.CharField(default='#0A192F', help_text='Color for the registration page heading', max_length=7),
        ),
        migrations.AddField(
            model_name='registrationpagesetting',
            name='subtitle_color',
            field=models.CharField(default='#6C757D', help_text='Color for the registration page subtitle', max_length=7),
        ),
    ]
