# Generated by Django 5.0.7 on 2025-10-26 08:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_compulsory', models.BooleanField(default=False, help_text='If true, this block will be auto-created when a page is saved')),
            ],
            options={
                'verbose_name': 'Block Type',
                'verbose_name_plural': 'Block Types',
            },
        ),
        migrations.CreateModel(
            name='CounterStatsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureHighlightsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroBannerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, help_text='Optional heading for the hero section', max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('intro', models.TextField(blank=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('is_published', models.BooleanField(default=True)),
                ('template_name', models.CharField(blank=True, help_text='Optional template to render this page', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StyleOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color (hex code)', max_length=7)),
                ('background_image', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='backgrounds/')),
                ('background_image_opacity', models.FloatField(default=1.0, help_text='Background image opacity (0.0-1.0)')),
                ('text_color', models.CharField(default='#212529', help_text='Text color (hex code)', max_length=7)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', help_text='Text alignment', max_length=10)),
                ('padding_top', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='medium', help_text='Top padding', max_length=10)),
                ('padding_bottom', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='medium', help_text='Bottom padding', max_length=10)),
                ('padding_left', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Left padding', max_length=10)),
                ('padding_right', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Right padding', max_length=10)),
                ('margin_top', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Top margin', max_length=10)),
                ('margin_bottom', models.CharField(choices=[('none', 'None (0px)'), ('small', 'Small (20px)'), ('medium', 'Medium (40px)'), ('large', 'Large (80px)'), ('xl', 'Extra Large (120px)')], default='none', help_text='Bottom margin', max_length=10)),
                ('container_width', models.CharField(choices=[('full', 'Full Width'), ('boxed', 'Boxed'), ('narrow', 'Narrow')], default='boxed', help_text='Container width', max_length=10)),
                ('border_radius', models.PositiveIntegerField(default=8, help_text='Border radius in pixels (0-50)')),
                ('shadow', models.BooleanField(default=False, help_text='Add shadow effect')),
                ('animate_on_scroll', models.BooleanField(default=True, help_text='Enable scroll animations')),
                ('hover_effect', models.CharField(choices=[('none', 'No Effect'), ('lift', 'Lift Up'), ('zoom', 'Zoom In'), ('fade', 'Fade'), ('glow', 'Glow')], default='none', help_text='Hover effect for the block', max_length=20)),
                ('custom_class', models.CharField(blank=True, help_text='Additional CSS classes', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Style Options',
                'verbose_name_plural': 'Style Options',
            },
        ),
        migrations.CreateModel(
            name='CounterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='page_content.counterstatsblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='page_content.faqblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='page_content.featurehighlightsblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blocks/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page_content.galleryblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='blocks/hero/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='page_content.herobannerblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('url', models.CharField(blank=True, help_text='Optional absolute or relative URL', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page_content.menuitem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='page_content.page')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='herobannerblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page'),
        ),
        migrations.AddField(
            model_name='galleryblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page'),
        ),
        migrations.AddField(
            model_name='featurehighlightsblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page'),
        ),
        migrations.AddField(
            model_name='faqblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page'),
        ),
        migrations.AddField(
            model_name='counterstatsblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Block Content')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='page_content.blocktype')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='page_content.page')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='herobannerblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions'),
        ),
        migrations.AddField(
            model_name='galleryblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions'),
        ),
        migrations.CreateModel(
            name='FooterInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('links_json', models.JSONField(blank=True, help_text='Optional array of links: [{name, url}]', null=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='featurehighlightsblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions'),
        ),
        migrations.AddField(
            model_name='faqblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions'),
        ),
        migrations.AddField(
            model_name='counterstatsblock',
            name='style_options',
            field=models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions'),
        ),
        migrations.CreateModel(
            name='ContactFormBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallToActionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPreviewBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('count', models.PositiveIntegerField(default=3)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMemberBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMemberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blocks/team/')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='page_content.teammemberblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestimonialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blocks/testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='page_content.testimonialblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TextImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/text_image/')),
                ('alignment', models.CharField(choices=[('left', 'Image Left'), ('right', 'Image Right')], default='left', max_length=5)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='page_content.timelineblock')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TwoColumnTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('left_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Left Text')),
                ('right_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Right Text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoEmbedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('embed_url', models.URLField(help_text='YouTube/Vimeo embed URL')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
