# Generated by Django 5.0.7 on 2025-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_content', '0002_copy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleoptions',
            name='background_gradient',
            field=models.TextField(blank=True, help_text='CSS gradient value (e.g., linear-gradient(45deg, #ff0000, #0000ff))'),
        ),
        migrations.AddField(
            model_name='styleoptions',
            name='background_type',
            field=models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='color', help_text='Type of background to use', max_length=10),
        ),
    ]
