# Generated by Django 5.0.7 on 2025-10-27 13:52

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_content', '0003_styleoptions_background_gradient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyledContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the content block', max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for the block', verbose_name='Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_%(class)s', to='page_content.page')),
                ('style_options', models.OneToOneField(blank=True, help_text='Custom styling options for this block', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_content.styleoptions')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
